# Generated by Django 4.1.3 on 2022-12-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='created_by',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
