# Generated by Django 4.1.4 on 2022-12-27 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_poll_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='deadline',
            field=models.DateField(default=datetime.datetime(2022, 12, 27, 12, 47, 54, 17751)),
        ),
    ]
